// webpack-tutorial/webpack-review02/src/APP.vue
<template>
    <div>
        <div v-for="item of musics" :key="item.id">
           <p>{{item.name}}</p>
           <img :src="item.coverImgUrl" alt="">
        </div>
    </div>
</template>
<script>
import axios from 'axios'
export default {
    name:"App",
    data(){
        return{
            musics:[]
        }
    },
    mounted(){
       var url="http://192.168.14.49:3000/top/playlist?cat=日语"
      /*  this.axios(url).then(res=>{
           console.log(res)
       }) */
       axios.get(url).then(res=>{
           this.musics=res.data.playlists;
       })
    }
}
</script>
<style scoped>
    
</style>

// react/react-demo04/src/App.js
import React from 'react';
import Title from './components/Title'
import axios from 'axios'
class App extends React.Component{
  constructor(props){
    super(props);
    this.state={
      msg:"hello world",
      playlists:[]
    }
  }
  render(){
    return(
      <div>
        <Title 
        //1.子组件的属性接收父组件传递过来的方法
        deleteItem={this.handleDelete.bind(this)}
        msg={this.state.msg}></Title>
        {this.state.playlists.map(item=>{
          return (<div key={item.id}>
          <p>{item.name}</p></div>)
        })}
      </div>
    )
  }
  handleDelete(id){
    console.log(id)
  }
  componentDidMount(){
    var url='https://music.aityp.com/top/playlist?cat=华语'
    this.$http.get(url).then(res=>{
      var playlists=res.data.playlists;
      this.setState({
        playlists
      })
    })
  }
}


export default App;
