// react/react-demo04/src/App.js
import React from 'react';
import Title from './components/Title'
import axios from 'axios'
class App extends React.Component{
  constructor(props){
    super(props);
    this.state={
      msg:"hello world",
      playlists:[]
    }
  }
  render(){
    return(
      <div>
        <Title 
        //1.子组件的属性接收父组件传递过来的方法
        deleteItem={this.handleDelete.bind(this)}
        msg={this.state.msg}></Title>
        {this.state.playlists.map(item=>{
          return (<div key={item.id}>
          <p>{item.name}</p></div>)
        })}
      </div>
    )
  }
  handleDelete(id){
    console.log(id)
  }
  componentDidMount(){
    var url='https://music.aityp.com/top/playlist?cat=华语'
    this.$http.get(url).then(res=>{
      var playlists=res.data.playlists;
      this.setState({
        playlists
      })
    })
  }
}


export default App;

// vue/01vue-demo/src/App.vue
<template>
  <div id="app">
    <div class="item" v-for="item of movies" :key="item.id">
      <p>{{item.title}}</p>
      <img :src="item.images.small" alt="">
    </div>
  </div>
</template>

<script>
import axios from 'axios-jsonp-pro';
export default {
  name: 'app',
  data(){
    return{
     movies:[]
    };
  },
  methods:{
    handleClick(){
      this.msg="change"
    }
  },
  mounted(){
    var url="https://douban.uieee.com/v2/movie/top250";
    axios.jsonp(url).then(res=>{
     console.log(res)
    })
  }
}
</script>
