// react/react-demo04/src/App.js
import React from 'react';
import Title from './components/Title'
import axios from 'axios'
class App extends React.Component{
  constructor(props){
    super(props);
    this.state={
      msg:"hello world",
      playlists:[]
    }
  }
  render(){
    return(
      <div>
        <Title 
        //1.子组件的属性接收父组件传递过来的方法
        deleteItem={this.handleDelete.bind(this)}
        msg={this.state.msg}></Title>
        {this.state.playlists.map(item=>{
          return (<div key={item.id}>
          <p>{item.name}</p></div>)
        })}
      </div>
    )
  }
  handleDelete(id){
    console.log(id)
  }
  componentDidMount(){
    var url='https://music.aityp.com/top/playlist?cat=华语'
    this.$http.get(url).then(res=>{
      var playlists=res.data.playlists;
      this.setState({
        playlists
      })
    })
  }
}


export default App;

// webpack-tutorial/webpack-start01/src/App.vue
<template>
    <div class="container">
       <div v-for="item of musics" :key="item.id">
           <img :src="item.coverImgUrl" alt="">
           <p>{{item.name}}</p>
       </div>
    </div>
</template>

<script>
import axios from 'axios'
    export default {
        name:"App",
        data(){
            return{
                musics:[]
            }
        },
        mounted(){
            var url="https://music.aityp.com/top/playlist?cat=华语"
            axios.get(url).then(res=>{
                var musics=res.data.playlists;
                console.log(musics)
                this.musics=musics;
            })
        }
    }
</script>

<style lang="scss" scoped>

</style>
